name: auto deploy

on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: yarn install, build
        run: |
          yarn install
          yarn build --base-href "https://heya-naohiro.github.io/coffee-brewtimer/"
          cp -a dist/coffee-brewtimer/index.html dist/coffee-brewtimer/404.html
        env:
          CI: true
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist/coffee-brewtimer
          CLEAN: true

        
          
